name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore "src/api/Api.csproj"
    - name: Build
      run: dotnet build "src/api/Api.csproj" --configuration Release --no-restore
    - name: Test
      run: dotnet test "src/api/Api.csproj" --no-restore --verbosity normal
