name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore "src/api/Api.csproj"

    - name: Build
      run: dotnet build "src/api/Api.csproj" --configuration Release --no-restore -o out
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: artifact-api
        path: out
        if-no-files-found: error
        retention-days: 90
