name: Build Frame Dex

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-api:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set .NET Core SDK version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install Api dependencies
      run: dotnet restore "src/api/Api.csproj"

    - name: Build Api project
      run: dotnet build "src/api/Api.csproj" --configuration Release --no-restore

    - name: Create Api release artifacts
      run: dotnet publish "src/api/Api.csproj" --configuration Release --no-restore --no-build --output dist
      
    - name: Zip Api release artifacts
      uses: Amadevus/pwsh-script@v2.0.0
      with:
        script: Compress-Archive -Path dist/* -DestinationPath dist/api.zip
      
    - name: Upload Api zipped artifacts
      uses: actions/upload-artifact@v2.2.1
      with:
        name: api
        path: dist/api.zip
        if-no-files-found: error
        retention-days: 90
