name: Build Frame Dex

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-api:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set .NET Core SDK version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install Api dependencies
      run: dotnet restore "src/api/Api.csproj"

    - name: Build Api
      run: dotnet build "src/api/Api.csproj" --configuration Release --no-restore

    - name: Publish Api
      run: dotnet publish "src/api/Api.csproj" --configuration Release --no-restore --no-build --output dist
      
    - name: Upload Api Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: api
        path: dist
        if-no-files-found: error
        retention-days: 90
